spring:
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: create-drop

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect